### ISSUE TITLE
Linux doorstop support

### ISSUE THREAD

**Issue by ljoonal** [MonkeyModdingTroop/MonkeyLoader#2]
Could just bundle the linux release's few extra needed files to not need to have separate windows & linux versions; libdoorstop.so file and the `run.sh` file with the `executable_name="Resonite.x86_64"` (or empty I guess if distributed in the MonkeyLoader project and not with resonite) & `target_assembly="MonkeyLoader/MonkeyLoader.dll"` replacements. Tho would be neat if they  could also be moved to be under the MonkeyLoader folder to not pollute the top level folder too much :stuck_out_tongue: 

Also probably should replace the doorstop links of `run.sh` to point issues to come here instead.

**Comment by ljoonal** [comment]
...eeexcept no this should be bundled with the unity gamepack shouldn't it...? But then that is just distributed as a nuget package where this repo's releases have a full `.zip` file...

**Comment by Banane9** [comment]
I mean, probably best to put the template into the main monkeyloader repo and then add the resonite one here
