### ISSUE TITLE
MonkeyLoader and the Monkeyloader mods not working anymore

### ISSUE THREAD

**Issue by Scrapper1824** [MonkeyModdingTroop/MonkeyLoader#35]
the MonkeyLoader mods are not loading and the the setting UI ether but the rml mods are running so im not sure what happend so i moved back to rml for now till this gets fix geussing that its probably not stable
hoping this can get fixed

![Screenshot 2024-08-20 170426](https://github.com/user-attachments/assets/c0e6e8ab-b80c-4b09-94dc-d4616c7f311e)

**Comment by Banane9** [comment]
If you don't provide any further details such as logs, we can't exactly do anything with this information

**Comment by Scrapper1824** [comment]
sorry for that i will get you logs when i have time

**Comment by Banane9** [comment]
I've also made a new release yesterday, so be sure to try with that

**Comment by Banane9** [comment]
Closing this now, comment if there's still an issue...
